; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
extra_configs =
	      secrets.ini
	      local.ini

[node32s]
platform = espressif32
framework = arduino
board = esp32dev
board_build.filesystem = littlefs
monitor_speed = 115200
check_tool = cppcheck
check_skip_packages = yes
monitor_filters = esp32_exception_decoder
build_type = release
board_build.partitions = min_spiffs.csv
extra_scripts = pre:build_svelte.py
lib_deps =
	chl33/og3@^0.6.4
	chl33/og3x-oled@^0.6.1
	chl33/og3x-shtc3@^0.6.0
	adafruit/Adafruit BusIO
	adafruit/Adafruit SHTC3 Library
	adafruit/Adafruit Unified Sensor
	bakercp/CRC32
	bblanchon/ArduinoJson@^7.0.0
	elims/PsychicMqttClient@^0.2.4
	hoeken/PsychicHttp@^2.1.1
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	SPI
	Wire
	WiFi

# Default values for hardware options
have_motion_light = 0
have_motion = 0
have_leak = 0
have_oled = 0
board_v10 = 0
upload_protocol = esptool
upload_port = /dev/ttyUSB0

build_flags =
	'-Wall'
	${local.build_flags}
	'-D OTA_PASSWORD="${secrets.otaPassword}"'
	'-D HAVE_MOTION_LIGHT=${this.have_motion_light}'
	'-D HAVE_MOTION=${this.have_motion}'
	'-D HAVE_LEAK=${this.have_leak}'
	'-D HAVE_OLED=${this.have_oled}'
	'-D BOARD_V10=${this.board_v10}'

lib_ldf_mode = deep+
lib_compat_mode = strict

[usb]
upload_protocol = esptool
upload_port = /dev/ttyUSB0
